"""Detect models again

Revision ID: 8a377ae80de2
Revises: 
Create Date: 2025-04-23 23:31:00.996969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a377ae80de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archive_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gas_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_km', sa.Integer(), nullable=True),
    sa.Column('end_km', sa.Integer(), nullable=True),
    sa.Column('fuel_price_per_liter', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cumulative_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cumulative_race_count', sa.Integer(), nullable=False),
    sa.Column('current_period_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_period_race_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['current_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['current_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('earnings')
    op.drop_table('current_cycle')
    op.drop_table('archives')
    # ### end Alembic commands ###
